# This file contains all default settings
# Do not edit this file
# Instead make all custom changes in .ini file


import os
import configparser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
GAMES_DIR = os.path.join(BASE_DIR, "games")
TEST_DIR = os.path.join(BASE_DIR, "test")
RUNNERS_DIR = os.path.join(TEST_DIR, "runners")

# Following keys have to be reassigned in .ini (loaded below).
LOCAL_INI_FILE = os.path.join(BASE_DIR, 'settings.ini')

#
# Game parameters

# Number of turns before game ends by timeout
# -1 means that game can't be over by timeout
TURNS_LIMIT = 100

#
# Field parameters
FIELD_WIDTH = 1000
FIELD_HEIGHT = 1000

#
# Parameters of generation

# Distance between border and spawn in cells
SPAWN_BORDER_GAP = 1
# Distance between spawns in cells
SPAWNS_DISTANCE = 1
# # Number of spawns for each team
# SPAWNS_NUMBER = 1
# Initial number of warriors
WARRIORS_INIT_NUMBER = 10
# # Number of players
# PLAYERS_NUMBER = 2

#
# Cells parameters

# Limit of warriors on one cell
# -1 means no limit
WARRIORS_LIMIT = 100

# Grow coefficient
GROW_COEFFICIENT = 2


##
# Local settings of the server (from the .ini config).
if os.path.isfile(LOCAL_INI_FILE):
    config = configparser.ConfigParser()
    config.optionxform = lambda option: option
    config.read(LOCAL_INI_FILE)

    for sec in config.sections():
        if sec == "GENERAL":
            for key in config[sec]:
                try:
                    globals()[key] = int(config[sec][key])
                except ValueError:
                    globals()[key] = config[sec][key]
        else:
            pass
